# Generated by Django 4.0.1 on 2022-05-25 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('criminal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256, null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Criminals',
            },
        ),
    ]
